# Generated by Django 2.1.2 on 2018-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181027_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='salary',
        ),
        migrations.AddField(
            model_name='person',
            name='rfid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
